### ISSUE TITLE
Spell checking service focusing on Finnish, is no longer operational since Libreoffice v. 6.1.4.2 release on Linux.

### ISSUE THREAD

**Issue by Ricky-Tigg** [voikko/libreoffice-voikko#11]
Hi. Till _Libreoffice_ version **6.1.2.1** release, on **x86-64 (AMD64)** hardware architecture, using _Linux_, _Fedora_ **last stable** variant release, the **spell checking** service focusing on text written in Finnish have been operational. Next maintenance brought _Libreoffice_ version **6.1.4.2** release to _Fedora_; since then, that service have not been operational.
Though system configuration has remained in the state that prevailed when that service was still operational. On that [page](https://extensions.libreoffice.org/extensions/finnish-spell-checker-and-hyphenator-voikko), I could assume that, mentioned compatibility with _Libreoffice_ last stable version – **6.1** – is still actual, as I conceived it could not end that way without formal notification from the author of the present language extension.

**Comment by Ricky-Tigg** [comment]
**LibreOffice** used:
_Versio: 6.2.5.2; Käännöksen ID: 6.2.5.2-1.fc30; CPU-säikeet: 2; Käyttöjärjestelmä: Linux 5.1; Piirtokomponentti: oletus; VCL: gtk3; Maa-asetus: fi-FI (fi_FI.UTF-8); Käyttöliittymän kieli: fi-FI; Calc: threaded_

Hi. You may have by now by yourself confirmed, possibly on a virtual machine with the last Fedora system installed selecting Finnish as system language and leaving the systems with its defaults settings, the observation presently reported, which goes on. It may be challenging to determine on whose side the issue sits. Once you have a fully updated system by running `sudo dnf --refresh -qy upgrade` the following commands could be run.

Here are the functions that determine which packages are currently installed by default.
```
$ dnf -q list installed *langpack* | grep -ie -fi.
glibc-langpack-fi.x86_64                   2.29-15.fc30           @updates        
langpacks-fi.noarch                        1.0-17.fc30            @fedora         
libreoffice-langpack-fi.x86_64             1:6.2.5.2-1.fc30       @updates
```
```
$ dnf -q list installed *voikko*
Asennetut paketit
enchant-voikko.x86_64                      1:1.6.0-23.fc30        @fedora 
enchant2-voikko.x86_64                     2.2.5-1.fc30           @updates
libreoffice-voikko.x86_64                  5.0-3.fc30             @fedora 
libvoikko.x86_64                           4.1.1-2.fc30           @fedora 
malaga-suomi-voikko.x86_64                 1.19-9.fc30            @fedora 
python3-libvoikko.noarch                   4.1.1-2.f              @fedora 
```

The following command produces same output without option `--installed`. These are the required packages that are also installed on the system.
```
$ dnf -q repoquery --installed --resolve --requires libreoffice-voikko | more
libreoffice-core-1:6.2.5.2-1.fc30.x86_64
libreoffice-pyuno-1:6.2.5.2-1.fc30.x86_64
python3-libvoikko-0:4.1.1-2.fc30.noarch
```
That would get the complete list with indirect dependencies:
`$ dnf -q repoquery --recursive --resolve --requires libreoffice-voikko`

That would get the complete list with indirect dependencies installed:
`$ dnf -q repoquery --installed  --recursive --resolve --requires libreoffice-voikko`

Output produced by selecting libreoffice-voikko for removing:
```
$ LANG=C sudo dnf remove libreoffice-voikko
Dependencies resolved.
================================================================================
 Package                     Arch       Version              Repository    Size
================================================================================
Removing:
 libreoffice-voikko          x86_64     5.0-3.fc30           @fedora      137 k
Removing dependent packages:
 libreoffice-langpack-fi     x86_64     1:6.2.5.2-1.fc30     @updates     2.6 M
```

**Comment by hatapitk** [comment]
Hi!

Thanks for the detailed additional information. It looks like you have libvoikko 4.1.1 and malaga-suomi-voikko 1.19 installed. This combination does not work in the default configuration. I am not sure what build configuration Fedora uses for libvoikko but this might be the reason why spell checking is not working properly. Running
`voikkospell -l`
will reveal if libvoikko cannot find compatible dictionary. But I don't know which package in Fedora contains the voikkospell binary.

Based on the information you provided and my own testing on Debian where this bug cannot be reproduced I will label this a downstream bug and suggest reporting it to Fedora bug tracker.

**Comment by Ricky-Tigg** [comment]
Hi. You will be reported at [Red Hat Bugzilla](https://bugzilla.redhat.com/), under package _voikko-tools_.
```
$ LANG=C voikkospell -l
fi-x-standard: suomi (perussanasto)
$ rpm -ql $(rpm -qf `which voikkospell` --qf '%{NAME}\n')
/usr/bin/voikkogc
/usr/bin/voikkohyphenate
/usr/bin/voikkospell
/usr/lib/.build-id
/usr/lib/.build-id/47
/usr/lib/.build-id/47/9aabc9e074b8b5734a006575a12d0e8fc45aa8
/usr/lib/.build-id/b4
/usr/lib/.build-id/b4/b551fd7f9ec4dfd6b882572a8fb69bc5b78595
/usr/lib/.build-id/e1
/usr/lib/.build-id/e1/85fbae1db34e32465602b3576d04c8c68b9b45
/usr/share/man/man1/voikkogc.1.gz
/usr/share/man/man1/voikkohyphenate.1.gz
/usr/share/man/man1/voikkospell.1.gz
```

**Comment by Ricky-Tigg** [comment]
Referenced first at closest [downstream](https://bugs.documentfoundation.org/show_bug.cgi?id=122984) then at next closest [downstream](https://bugzilla.redhat.com/show_bug.cgi?id=1734708) under component _libvoikko_.

**Comment by caolanm** [comment]
The install-unpacked target in the Makefile loses the necessary hierarchy at install

**Comment by Ricky-Tigg** [comment]
@caolanm  – Issue [Gnome – #103](https://gitlab.gnome.org/GNOME/gedit/issues/103) might also be eligible under _resolves_ at 83e27fc.

**Comment by Ricky-Tigg** [comment]
@caolanm /Red Hat – Thanks; you resolved that @hatapitk's case.
