### ISSUE TITLE
Feature request: manually specified dict search path

### ISSUE THREAD

**Issue by snomos** [voikko/libreoffice-voikko#3]
It would be very useful to be able to manually specify additional search paths in the LO-voikko oxt settings pane. The specified path(s) would then be searched first, and would give the user a way to specify search paths not considered when the oxt was compiled.

**Comment by hatapitk** [comment]
Libvoikko has no API that would allow doing this right now. I'd like to understand the use case better. Is this something that ordinary users would likely need?

You can already specify additional paths by setting the environment variable VOIKKO_DICTIONARY_PATH before you start the program that uses libvoikko:
<pre>
VOIKKO_DICTIONARY_PATH=/home/harri/something:/usr/local/other lowriter
</pre>

Users who directly access paths such as /usr/local/share/voikko are likely able to use this method. It also works for other applications (Mozvoikko etc.). Would this be enough?

**Comment by snomos** [comment]
Using the environment variable should be ok.

**Comment by hatapitk** [comment]
Ok, I will close this as enhancement/wontfix for now. But in theory this might work as an advanced option as long as the UI won't confuse casual users.
