### ISSUE TITLE
 libreoffice-voikko -- No  man page; no obvious way to invoke

### ISSUE THREAD

**Issue by Lew-Rockwell-Fan** [voikko/libreoffice-voikko#9]
Under Ubuntu 16.04 I installed thus:
sudo apt-get install --no-install-recommends libreoffice-voikko
No obvious way to invoke it. No man page. Can this be used stand-alone spell checker? I don't want a ton of libre-office stuff.

**Comment by hatapitk** [comment]
It is an extension to LibreOffice and thus cannot be used as stand-alone spell checker. The package only recommends certain LibreOffice packages to allow the user the choice of installing only Writer or Calc etc.

If you need a stand-alone spell checker you can use tmispell-voikko or enchant.
